server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 9090

spring:
  datasource:
    driver-class-name: com.tandem.sqlmx.SQLMXDriver
    url: "jdbc:sqlmx:"
    hikari:
      catalog: mallcat
      schema: mallsch

# 自訂參數
custom:
  osType: OSS
#    url= jdbc:sqlserver://localhost;databaseName=testmall;encrypt=true;trustServerCertificate=true
#    username: boss
#    password: boss
#  mvc:
#    converters:
#      preferred-json-mapper: gson

#spring.http.encoding.charset=UTF-8
#spring.http.encoding.force=true
#spring.http.encoding.enable=true
